// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "integrityioctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CIntegrityioctrl1

IMPLEMENT_DYNCREATE(CIntegrityioctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIntegrityioctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CIntegrityioctrl1 operations
