#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIntegritybargrapctrl1 wrapper class

class CIntegritybargrapctrl1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CIntegritybargrapctrl1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x6C8AF639, 0xE23A, 0x4041, { 0xB6, 0xB2, 0x33, 0x3, 0xD7, 0xD0, 0xE0, 0x66 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:


// Operations
public:

// _DIntegrityBarGraph

// Functions
//

	void AboutBox()
	{
		InvokeHelper(DISPID_ABOUTBOX, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
	}
	double get_dElement(unsigned short index)
	{
		double result;
		static BYTE parms[] = VTS_UI2 ;
		InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms, index);
		return result;
	}
	void put_dElement(unsigned short index, double newValue)
	{
		static BYTE parms[] = VTS_UI2 VTS_R8 ;
		InvokeHelper(0x4, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, index, newValue);
	}
	CString get_strElementTitle(unsigned short index)
	{
		CString result;
		static BYTE parms[] = VTS_UI2 ;
		InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms, index);
		return result;
	}
	void put_strElementTitle(unsigned short index, LPCTSTR newValue)
	{
		static BYTE parms[] = VTS_UI2 VTS_BSTR ;
		InvokeHelper(0x5, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms, index, newValue);
	}

// Properties
//

double GetdblMaxValue()
{
	double result;
	GetProperty(0x1, VT_R8, (void*)&result);
	return result;
}
void SetdblMaxValue(double propVal)
{
	SetProperty(0x1, VT_R8, propVal);
}
double GetdblMinValue()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}
void SetdblMinValue(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}
long GetlnNumElements()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}
void SetlnNumElements(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}


};
