// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "integritybargrapctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CIntegritybargrapctrl1

IMPLEMENT_DYNCREATE(CIntegritybargrapctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIntegritybargrapctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CIntegritybargrapctrl1 operations
