// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "integritylinegractrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CIntegritylinegractrl1

IMPLEMENT_DYNCREATE(CIntegritylinegractrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIntegritylinegractrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CIntegritylinegractrl1 operations
